In [13]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd
import csv
import random
import math
import operator
from numpy.linalg import inv
df = pd.read_csv("AdmissionDataset/data.csv")

In [14]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [15]:
from sklearn.model_selection import train_test_split  
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 
train,test = train_test_split(df, test_size=0.2) 

In [16]:
train_y = train['Chance of Admit ']
train = train.drop('Serial No.',axis=1)
train = train.drop('Chance of Admit ',axis=1)
test_y = test['Chance of Admit ']
test = test.drop('Serial No.',axis=1)
test = test.drop('Chance of Admit ',axis=1)
test.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
110        314          109                  4  3.5   4.0  8.77         1
211        324          112                  4  4.0   2.5  8.10         1
235        310          106                  4  4.5   4.5  9.04         1
327        307          109                  3  4.0   3.0  8.00         1
332        317          106                  3  3.5   3.0  7.89         1

In [17]:
X=train.values
z = np.ones((len(train),1))
X=np.append(z,X, axis=1)

In [18]:
(X)

array([[  1.  , 322.  , 112.  , ...,   2.5 ,   9.02,   1.  ],
       [  1.  , 330.  , 116.  , ...,   3.5 ,   9.23,   1.  ],
       [  1.  , 316.  , 109.  , ...,   3.5 ,   8.76,   1.  ],
       ...,
       [  1.  , 317.  , 103.  , ...,   2.  ,   8.15,   0.  ],
       [  1.  , 331.  , 112.  , ...,   5.  ,   9.8 ,   1.  ],
       [  1.  , 310.  , 105.  , ...,   3.5 ,   8.01,   0.  ]])

In [19]:
X_trans=X.T

In [20]:
temp=np.dot(X_trans,X)
inv1=inv(temp)

In [21]:
# ar=np.array([[1,2,3],[4,5,6]])
# b=np.array([[2],[1],[1]])
# temp2=np.dot(ar,b)
# temp2
# inv1

In [22]:
temp2=np.dot(inv1,X_trans)

In [23]:
temp2.shape

(8, 360)

In [26]:
# y.shape

In [27]:
beta=np.dot(temp2,train_y)

In [28]:
beta

array([-1.32751455,  0.00206133,  0.00251783,  0.0031909 ,  0.0043926 ,
        0.01523502,  0.12069423,  0.0258457 ])

In [29]:
# df.head

In [30]:
X.shape

(360, 8)

In [31]:
z = np.ones((len(test),1))
tt=np.append(z,test, axis=1)
len(tt)

90

In [32]:
y_pred=np.dot(tt,beta)

In [33]:
y_pred.shape

(90,)

In [34]:
y_pred

array([0.76759699, 0.69424236, 0.79639576, 0.64400352, 0.64159064,
       0.54346791, 0.49188943, 0.71797015, 0.73699442, 0.69409224,
       0.82714768, 0.6945946 , 0.75973588, 0.84637244, 0.98277123,
       0.73462141, 0.68666812, 0.62309665, 0.73686854, 0.83014868,
       0.89414883, 0.63786754, 0.77276325, 0.72106311, 0.68771827,
       0.67097996, 0.8615534 , 0.74849257, 0.65385395, 0.66610764,
       0.69745481, 0.5955997 , 0.62281114, 0.53117055, 0.83994009,
       0.62080414, 0.62215404, 0.8047812 , 0.83691175, 0.78206836,
       0.59798574, 0.75257673, 0.71884145, 0.65832924, 0.82477826,
       0.93489571, 0.77993366, 0.50772399, 0.78363079, 0.53731233,
       0.91051366, 0.72053771, 0.96500176, 0.79120333, 0.89569619,
       0.62113962, 0.52374776, 0.70059544, 0.88869708, 0.82747799,
       0.45162454, 0.53136727, 0.50761962, 0.59732968, 0.58385833,
       0.68760033, 0.54242735, 0.81988374, 0.85365195, 0.82831236,
       0.81702223, 0.85939612, 0.88896419, 0.58434579, 0.61567

In [35]:
# test_y

In [36]:
# np.append(z,X, axis=1)
from sklearn.model_selection import train_test_split  
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 

# Part 2

### Mean squared error

In [37]:
MSE=((y_pred-test_y)**2).sum()/len(test_y)

In [38]:
MSE

0.004774900696416725

### Mean Absolute Error

In [39]:
MAE=(abs(y_pred-test_y)).sum()/len(test_y)

In [40]:
MAE

0.048311116141873126

### Mean Percentage Error

In [41]:
MPE=(((y_pred-test_y)/test_y).sum()/len(test_y))*100

In [42]:
MPE

1.989711387185554

In [43]:
beta

array([-1.32751455,  0.00206133,  0.00251783,  0.0031909 ,  0.0043926 ,
        0.01523502,  0.12069423,  0.0258457 ])

In [44]:
# import matplotlib.pyplot as plt
# #print plot_arr
# plt.plot(beta)
# plt.show()

In [ ]:
#     from sklearn.model_selection import train_test_split  
#     X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) 
#     train,test = train_test_split(df, test_size=0.2) 
# #     random.seed(0)
#     pre_values=[]
#     k = 3
# #     print(X_test)
# #     temp=X_test.to_dict('records')
# #     print (temp[0])
#     test=test.values
#     train=train.values